### ISSUE TITLE
Docker Compose File

### ISSUE THREAD

**Issue by Felitendo** [debloper/xplex#21]
Please make a docker compose file :)

**Comment by nhalstead** [comment]
```compose.yaml

services:
    xplex:
        container_name: xplex
        ports:
            - 80:80 # Web UI
            - 1935:1935 # Stream Port
        image: ghcr.io/debloper/xplex:latest

```

**Comment by debloper** [comment]
@nhalstead thanks, can you please send a PR?

**Comment by ralyodio** [comment]
can we add a persistent data directory to that docker-compose file? So we can delete and restart without losing all user data?

**Comment by nhalstead** [comment]
> can we add a persistent data directory to that docker-compose file?

That's what pr #25 does
